### ISSUE TITLE
stored事件监听回调报错

### ISSUE THREAD

**Issue by kalomuse** [yyang/cfs-aliyun#9]
用Meteor-CollectionFS实现图片上传，图片储存完成后执行stored回调函数，在回调函数里执行相关Mongo数据库的操作会报错，我写的代码大概是这样的：
```html
img_stored = new Mongo.Collection("img_stored");
Images = new FS.Collection('images', {
    stores: [store]
});
let file = Images.findOne(fileId);
            file.on('stored', function() {
                img_stored.findOne({'fileId': this._id}, function() {
                
                });
            });
```
在执行update操作时update函数回调可以执行并且不报错，但不会进行数据库数据修改
错误如下：
```html
W20170110-13:07:47.367(8)? (STDERR) 200: null
W20170110-13:07:47.367(8)? (STDERR)     at Request.extractError (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/services/oss.js:147:37)
W20170110-13:07:47.368(8)? (STDERR)     at Request.callListeners (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)
W20170110-13:07:47.368(8)? (STDERR)     at Request.callListeners (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/sequential_executor.js:114:16)
W20170110-13:07:47.368(8)? (STDERR)     at Request.emit (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/sequential_executor.js:81:10)
W20170110-13:07:47.368(8)? (STDERR)     at Request.emit (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:389:14)
W20170110-13:07:47.368(8)? (STDERR)     at Request.transition (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:52:12)
W20170110-13:07:47.368(8)? (STDERR)     at AcceptorStateMachine.runTo (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:17:12)
W20170110-13:07:47.368(8)? (STDERR)     at /Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:29:10
W20170110-13:07:47.368(8)? (STDERR)     at Request.transition (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:66:7)
W20170110-13:07:47.368(8)? (STDERR)     at AcceptorStateMachine.runTo (/Users/apple/.meteor/packages/iyyang_cfs-aliyun/.0.1.2.2w4iiu++os+web.browser+web.cordova/npm/node_modules/aliyun-sdk/lib/request.js:17:12)
```

**Comment by streamliner18** [comment]
这段代码在cfs-aliyun之外的store上会报错吗？看起来应该是cfs-core的问题。
